language: objective-c
osx_image: xcode7

before_install: 
- brew update
- brew install carthage

install:
- carthage checkout
- carthage build --no-skip-current

script:
- xcodebuild build -scheme IDZSwiftCommonCryptoCarthageTest -destination 'platform=iOS Simulator,name=iPhone 6,OS=8.1' 
